name: reading a text file

on : push

jobs: 
   read-file-job:
      runs-on : ubuntu-latest
      steps: 
        - name: check out repo code
          uses: actions/checkout@v4   # in built action being used to checkout the repo
        - run : echo "$(cat random.txt)" # read the file